### ISSUE TITLE
Disambiguation of the ordering of important characters

### ISSUE THREAD

**Issue by Alestainer** [pyhawaii/talks#8]
Does string "51qwerty" produce "qr" or "rq" in the homemade puzzle?

**Comment by chalmerlowe** [comment]
@Alestainer Hmmm.

Based on my recollection, a simple `for each character in the text` algorithm would find the `5` and then count forward by five to find the `r`, skipping over the `1` entirely and thus the `1` would not be considered a pointer to the `r`.

If that is unclear, please let me know.

Interesting.

**Comment by chalmerlowe** [comment]
@Alestainer Did you find a substring with two numeric characters?
I just searched the raw text and did not find any.

**Comment by Alestainer** [comment]
@chalmerlowe it is an additional assumption (based on your solution) that algorithm will skip 5 characters. In the problem's set up it says "**Every** NUMBER identifies the location of a CHARACTER...". Based on this sentence, it is incorrect to skip 1

**Comment by chalmerlowe** [comment]
@Alestainer...
Thanks for asking the question... there should be no cases of such paired numbers.
If there are ... then my generator script is prolly an epic fail.
